// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef RECONSTRUCTION_H
#define RECONSTRUCTION_H

#include <ngrest/common/Service.h>

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: reconstruction
class Reconstruction: public ngrest::Service
{
public:

    std::string Reconstruction3D(std::string imgListFile,std::string uSer,std::string tIme,     std::string intMaxParallax,std::string 
                                intMinParallax, std::string intRowGridSize,std::string intColGridSize,std::string floatProjErrorThreshold,std::string floatDenoisingPara);

    std::string CSF_Filter(std::string pointCloudPath,std::string uSer,std::string tIme,std::string floatCSF_Size,std::string floatClassificationThreshold);

    std::string DEM_Interpolation(std::string groundPointCloudPath,std::string uSer,std::string tIme, 
                            std::string floatGridSize);


//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    //获取当前功能状态
    std::string GetTaskState_Service(std::string ProjPath, std::string pid);
    //终止当前任务
    std::string CancelCurrentWork_Service(std::string pid);
    // //查询当前任务是否终止
    // std::string CurrentWorkIsEnd(std::string ProjPath, std::string pid);
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

};


#endif // RECONSTRUCTION_H



